name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Build sdk
      run: xcodebuild  -project wulkanowy.xcodeproj -scheme Sdk build
      
    - name: Resolve package dependencies
      run: xcodebuild -resolvePackageDependencies
   
    - name: Clear cache
      run: rm -rf ~/Library/Developer/Xcode/DerivedData/ModuleCache
    
    - name: Build app
      run: xcodebuild CODE_SIGNING_ALLOWED=NO IPHONEOS_DEPLOYMENT_TARGET=14.4 -workspace wulkanowy.xcworkspace -scheme wulkanowy clean build


